### PR TITLE
Adjusted grammar (added commas) and typos for some of the documentation

### PR DESCRIPTION
**Pull request by natastro**
In response to #888 , I reviewed `README.md`, `WRITERS-NOTES.md`, `faq.md`, `api.md`, `architecture.md`, `glossary.md`, `interface.md`, `pmm-admin.md`, and `pmm-agent.md` for grammar and typos and revised as needed. @catalinaadam please let me know if you have any questions or concerns, thank you 😀

### CODE REVIEW

**Comment by natastro** [comment]
Note - I just signed the CLA above but it still shows as pending and as if I don't have a GitHub account. Any thoughts on how to fix this? Clicking the 'recheck' link didn't change anything.

**Comment by atymchuk** [comment]
> Note - I just signed the CLA above but it still shows as pending and as if I don't have a GitHub account. Any thoughts on how to fix this? Clicking the 'recheck' link didn't change anything.

No clue, I'll ask out internal IT to see why.

**Review by catalinaadam — APPROVED** [review]

**Comment by artemgavrilov** [comment]
@atymchuk any progress with CLA? Can we merge it without it?

**Comment by atymchuk** [comment]
> @atymchuk any progress with CLA? Can we merge it without it?

I created a ticket - https://percona.atlassian.net/servicedesk/customer/portal/2/HD-18283.
It has to do with our compliance, so let's see if IT can fix it.

**Comment by atymchuk** [comment]
@natastro OK, it seems we now know why CLA Assistant fails to recognize you as someone who signed the License Agreement. 

The issue is that you committed to this PR with a different email address than the one associated with your github `natastro` account.

To resolve this, either the original commits must be amended to reference the [outlook.com](http://outlook.com/) email address, or you have to add the [nku.edu](http://nku.edu/) address to you `natastro` GitHub account. 

Once done, try to follow the [CLA link from above](https://cla-assistant.percona.com/check/percona/pmm-doc?pullRequest=891) and it should solve it.

**Comment by natastro** [comment]
Hi @atymchuk - I moved emails on this account a couple years ago to the `outlook.com` email as it's my personal and most used. My GitHub was originally opened in undergrad under the `nku.edu` domain. I went back to check the settings on my account to make sure the email has been removed and all I see is the outlook one. Can you point me to any documentation on how to make my commits point to the outlook address? I apologize - I had assumed everything I created/updated was coming from that email.

**Comment by atymchuk** [comment]
> I had assumed everything I created/updated was coming from that email.

I ran a quick check with `git log` and I can see you were committing with your `@nku.edu` address. You can check what address you are committing with by running the following in your terminal: `git config --global user.email`.

You may want to read more about the implications [here](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user). I guess what you need to do is to change your commit email, i.e. `git config --global user.email "YOUR_EMAIL"`. That will solve it for any future contributions.

However, changing your email in your past commits would be error prone and take us all time to make it work. The best I can suggest is to close this PR and then resubmit it once your commit email matches the one on your github profile.

We apologize for any inconvenience and hope to see your PR resubmitted :)

**Comment by natastro** [comment]
Closing and resubmitting to adjust under new email address - n.stroud@outlook.com

**Pull request closed without merging**
