### PR TITLE
add badges

### PR DESCRIPTION
**Pull request by denisok**

### CODE REVIEW

**Comment by denisok** [comment]
@atymchuk any way to add render badge for `main` ?

**Comment by atymchuk** [comment]
> @atymchuk any way to add render badge for `main` ?

Not that I know... I believe it would give much less value compared to the other badges )

**Comment by denisok** [comment]
@atymchuk is https://pmm-doc.onrender.com/ actually a render for `main` ? maybe we could add it as a badge as well. As a rendered point to current state of the art before publishing for example.

**Comment by atymchuk** [comment]
> @atymchuk is https://pmm-doc.onrender.com/ actually a render for `main` ? maybe we could add it as a badge as well. As a rendered point to current state of the art before publishing for example.

It is.

**Review by atymchuk — APPROVED** [review]

**Review by rasika-chivate — APPROVED** [review]

**Review by atymchuk — APPROVED** [review]
🚢

**Pull request merged**
