### PR TITLE
Updated Grammatical and Spelling errors in LICENSE

### PR DESCRIPTION
**Pull request by WadekarPrashant**
Found 560 Errors including Grammatical as well as Spelling Errors.

Link of Errors Recognized:-
Free Grammar Checker _ QuillBot AI - Google Chrome 05-10-2022 14_42_30

Merge it if you really liked the changes!!
Thank You.

### CODE REVIEW

**Comment by WadekarPrashant** [comment]
@it-percona-cla please go through this
@AlekSi @atymchuk @fiowro

**Comment by atymchuk** [comment]
I went through the PR and I don't see any errors being corrected. It looks like removal of spaces, which probably of no added value given that all licenses on github are the same.

**Comment by AlekSi** [comment]
@atymchuk https://hacktoberfest.com/participation/#spam recommends adding `spam` label for such PRs

**Comment by WadekarPrashant** [comment]
@atymchuk I am really extremely sorry for that. I am a  newbie in this. i will never ever do this again. I will close the PR. Please remove it from spam its a request. please
Sorry @AlekSi i will never do that again.

**Pull request closed without merging**
