### PR TITLE
Clarify metric-mode flag

### PR DESCRIPTION
**Pull request by rnovikovP**

### CODE REVIEW

**Comment by rnovikovP** [comment]
could have a link to pmm-admin page when https://github.com/percona/pmm-doc/pull/311 finished

**Review by PaulJacobs-percona — COMMENTED** [review]
I will move this text to the new VM page and link to it. Because this is a highlights block, not meant for expansive explanations.

**Review by PaulJacobs-percona — CHANGES_REQUESTED** [review]
Moving info to own VM page to keep highlights highlighted.

**Comment by PaulJacobs-percona** [comment]
> could have a link to pmm-admin page when #311 finished

IMHO no need for a link to pmm-admin man page. This and pmm-admin are in the same major section (Details) and pmm-admin is mentioned frequently enough not to need to tell readers where to find more info on it.

**Pull request merged**
