### PR TITLE
PMM-7731 Update documentation with PSMDB 1.7v operator

### PR DESCRIPTION
**Pull request by beatahandzelova**

### CODE REVIEW

**Review by PaulJacobs-percona — APPROVED** [review]

**Comment by jprukner** [comment]
@PaulJacobs-percona please let me review before merging

**Comment by jprukner** [comment]
@PaulJacobs-percona We've got some issues with the upgrade on our side. We need to fix them first before merging this.

**Comment by PaulJacobs-percona** [comment]
@jprukner I replaced all instances of `v1.7.0` with a variable (in `variables.yml`) for easier maintenance. Please check all instances are the meant to be the same version.

**Comment by PaulJacobs-percona** [comment]
> @PaulJacobs-percona We've got some issues with the upgrade on our side. We need to fix them first before merging this.

No problem. You or @beatahandzelova can merge when you're ready and ping me to publish.

**Comment by beatahandzelova** [comment]
@PaulJacobs-percona the operators might not be released at the same time so we'll need separate variables; for pxc and psmdb

**Comment by PaulJacobs-percona** [comment]
@beatahandzelova What is the state of this change? Please complete or abandon it.

**Comment by jprukner** [comment]
@PaulJacobs-percona last change regarding this version change is in QA right now, we will merge this docs change today or tommorrow if everything is ok.

**Review by jprukner — APPROVED** [review]

**Pull request merged**
