### PR TITLE
Refresh virtual appliance

### PR DESCRIPTION
**Pull request by PaulJacobs-percona**

### CODE REVIEW

**Comment by PaulJacobs-percona** [comment]
Reviewers: This is a big rework of the original page. I expect no one person will click through all the steps. I did them but on macOS so there may be some errors due to that. Please read/execute whatever and comment on the technical stuff. 

But I'd also appreciate comments on the overall structure. There is a map (attached) that is supposed to visualise the effort. Although at this level both VMware and VB look the same, I would later like to add QEMU which makes the steps different.

Screenshot 2021-02-19 at 15 36 19

**Comment by PaulJacobs-percona** [comment]
@shoffman-percona @Nailya @puneet0191 @beatahandzelova Let me know if you're not going to help review this work and I'll find someone else. Just don't want it sitting here forever, thanks.

**Review by puneet0191 — APPROVED** [review]

**Comment by PaulJacobs-percona** [comment]
@puneet0191 Did you perform the steps or just read?

**Comment by PaulJacobs-percona** [comment]
Ticket for this work: https://jira.percona.com/browse/PMM-6424

**Pull request merged**
